import pandas as pd
data={
    "time(in seconds)":[],
    "bed pressure sensor":[],
    "bed sensor":[],
    "bedroom sensor":[],
    "kitchen sensor":[],
    "couch pressure sensor":[],
    "dinning chair pressure sensor":[],
    "bathroom sensor":[],
    "house sensor":[]
    }
for i in range(0,(24*3600)+1,5):
    if i%5000==0:
        print(i)
    data["time(in seconds)"].append(i)
    if i<7*3600:
        data["bed pressure sensor"].append(1)
        data["bed sensor"].append(0)
        data["bedroom sensor"].append(1)
        data["kitchen sensor"].append(0)
        data["couch pressure sensor"].append(0)
        data["dinning chair pressure sensor"].append(0)
        data["bathroom sensor"].append(0)
        data["house sensor"].append(1)
    if i==(7*3600)+5:
        data["bed pressure sensor"].append(0)
        data["bed sensor"].append(1)
        data["bedroom sensor"].append(1)
        data["kitchen sensor"].append(0)
        data["couch pressure sensor"].append(0)
        data["dinning chair pressure sensor"].append(0)
        data["bathroom sensor"].append(0)
        data["house sensor"].append(1)
    if i==(7*3600)+10:
        data["bed pressure sensor"].append(0)
        data["bed sensor"].append(0)
        data["bedroom sensor"].append(1)
        data["kitchen sensor"].append(0)
        data["couch pressure sensor"].append(0)
        data["dinning chair pressure sensor"].append(0)
        data["bathroom sensor"].append(0)
        data["house sensor"].append(1)
    if i>(7*3600)+10 and i<(7*3600)+615:
        data["bed pressure sensor"].append(0)
        data["bed sensor"].append(0)
        data["bedroom sensor"].append(1)
        data["kitchen sensor"].append(0)
        data["couch pressure sensor"].append(0)
        data["dinning chair pressure sensor"].append(0)
        data["bathroom sensor"].append(1)
        data["house sensor"].append(1)
    if i>=(7*3600)+615 and i<(7*3600)+630:
        data["bed pressure sensor"].append(0)
        data["bed sensor"].append(0)
        data["bedroom sensor"].append(1)
        data["kitchen sensor"].append(0)
        data["couch pressure sensor"].append(0)
        data["dinning chair pressure sensor"].append(0)
        data["bathroom sensor"].append(0)
        data["house sensor"].append(1)
    if i>=(7*3600)+630 and i<=8*3600:
        data["bed pressure sensor"].append(0)
        data["bed sensor"].append(0)
        data["bedroom sensor"].append(0)
        data["kitchen sensor"].append(0)
        data["couch pressure sensor"].append(1)
        data["dinning chair pressure sensor"].append(0)
        data["bathroom sensor"].append(0)
        data["house sensor"].append(1)
    if i>=(8*3600) and i<(8*3600)+1800:
        data["bed pressure sensor"].append(0)
        data["bed sensor"].append(0)
        data["bedroom sensor"].append(0)
        data["kitchen sensor"].append(1)
        data["couch pressure sensor"].append(0)
        data["dinning chair pressure sensor"].append(0)
        data["bathroom sensor"].append(0)
        data["house sensor"].append(1)
    if i>=(8*3600)+1800 and i<9*3600:
        data["bed pressure sensor"].append(0)
        data["bed sensor"].append(0)
        data["bedroom sensor"].append(0)
        data["kitchen sensor"].append(0)
        data["couch pressure sensor"].append(0)
        data["dinning chair pressure sensor"].append(1)
        data["bathroom sensor"].append(0)
        data["house sensor"].append(1)
    if i>=9*3600 and i<13*3600:
        data["bed pressure sensor"].append(0)
        data["bed sensor"].append(0)
        data["bedroom sensor"].append(0)
        data["kitchen sensor"].append(0)
        data["couch pressure sensor"].append(1)
        data["dinning chair pressure sensor"].append(0)
        data["bathroom sensor"].append(0)
        data["house sensor"].append(1)
    if i>=13*3600 and i<(13*3600)+1800:
        data["bed pressure sensor"].append(0)
        data["bed sensor"].append(0)
        data["bedroom sensor"].append(0)
        data["kitchen sensor"].append(1)
        data["couch pressure sensor"].append(0)
        data["dinning chair pressure sensor"].append(0)
        data["bathroom sensor"].append(0)
        data["house sensor"].append(1)
    if i>=(13*3600)+1800 and i<14*3600:
        data["bed pressure sensor"].append(0)
        data["bed sensor"].append(0)
        data["bedroom sensor"].append(0)
        data["kitchen sensor"].append(0)
        data["couch pressure sensor"].append(0)
        data["dinning chair pressure sensor"].append(1)
        data["bathroom sensor"].append(0)
        data["house sensor"].append(1)
    if i>=(14*3600) and i<18*3600:
        data["bed pressure sensor"].append(1)
        data["bed sensor"].append(0)
        data["bedroom sensor"].append(1)
        data["kitchen sensor"].append(0)
        data["couch pressure sensor"].append(0)
        data["dinning chair pressure sensor"].append(0)
        data["bathroom sensor"].append(0)
        data["house sensor"].append(1)
    if i>=18*3600 and i<20*3600:
        data["bed pressure sensor"].append(0)
        data["bed sensor"].append(0)
        data["bedroom sensor"].append(0)
        data["kitchen sensor"].append(0)
        data["couch pressure sensor"].append(0)
        data["dinning chair pressure sensor"].append(0)
        data["bathroom sensor"].append(0)
        data["house sensor"].append(0)
    if i >=20*3600 and i<(20*3600)+1800:
        data["bed pressure sensor"].append(0)
        data["bed sensor"].append(0)
        data["bedroom sensor"].append(0)
        data["kitchen sensor"].append(1)
        data["couch pressure sensor"].append(0)
        data["dinning chair pressure sensor"].append(0)
        data["bathroom sensor"].append(0)
        data["house sensor"].append(1)
    if i >= (20*3600)+1800 and i <21*3600:
        data["bed pressure sensor"].append(0)
        data["bed sensor"].append(0)
        data["bedroom sensor"].append(0)
        data["kitchen sensor"].append(0)
        data["couch pressure sensor"].append(0)
        data["dinning chair pressure sensor"].append(1)
        data["bathroom sensor"].append(0)
        data["house sensor"].append(1)
    if i>=21*3600 and i<22*3600:
        data["bed pressure sensor"].append(0)
        data["bed sensor"].append(0)
        data["bedroom sensor"].append(0)
        data["kitchen sensor"].append(0)
        data["couch pressure sensor"].append(1)
        data["dinning chair pressure sensor"].append(0)
        data["bathroom sensor"].append(0)
        data["house sensor"].append(1)
    if i>=22*3600:
        data["bed pressure sensor"].append(1)
        data["bed sensor"].append(0)
        data["bedroom sensor"].append(1)
        data["kitchen sensor"].append(0)
        data["couch pressure sensor"].append(0)
        data["dinning chair pressure sensor"].append(0)
        data["bathroom sensor"].append(0)
        data["house sensor"].append(1)
df=pd.DataFrame(data)
df.to_excel('modelday.xlsx',index=False)
print("done")
